export default {
    navList: [{
        title: '记录查询',
        sort: '1',
        icon: 'icon-jilu1-copy',
        secondNav: [{
            secondTitle: "全部记录",
            router: 'list1_1',
            icon: 'icon-quanbu'
        }, {
            secondTitle: "卡密记录",
            router: 'list1_2',
            icon: 'icon-qiami'
        }, {
            secondTitle: "扫码记录",
            router: 'list1_3',
            icon: 'icon-saoma'
        }, {
            secondTitle: "支付记录",
            router: 'list1_4',
            icon: 'icon-zhifu'
        }, {
            secondTitle: "激活记录",
            router: 'list1_5',
            icon: 'icon-daohanglan-tuijianclick'
        }]
    }, {
        title: '代充平台',
        sort: '2',
        icon: 'icon-daohanglanyijipaixingbangactive',
        secondNav: [{
            secondTitle: "批量充值",
            router: 'list2_1',
            icon: 'icon-piliang'
        }, {
            secondTitle: "油卡代充",
            router: 'list2_2',
            icon: 'icon-jiayouka'
        }, {
            secondTitle: "话费代充",
            router: 'list2_3',
            icon: 'icon-huafei'
        }]
    }, {
        title: '商品管理',
        sort: '3',
        icon: 'icon-houtaidaohanglan_shangpin',
        secondNav: [{
            secondTitle: "商品管理",
            router: 'list3_1',
            icon: 'icon-shangpin'
        }]
    }, {
        title: '生成激活',
        sort: '4',
        icon: 'icon-piliang',
        secondNav: [{
            secondTitle: "充值卡激活",
            router: 'list4_1',
            icon: 'icon-qiami'
        }, {
            secondTitle: "扫码卡激活",
            router: 'list4_2',
            icon: 'icon-saoma'
        }, {
            secondTitle: "充值卡生成",
            router: 'list4_2',
            icon: 'icon-qiami'
        }, {
            secondTitle: "扫码卡生成",
            router: 'list4_3',
            icon: 'icon-saoma'
        }]
    }, {
        title: '统计管理',
        sort: '5',
        icon: 'icon-houtaidaohanglan_shuju',
        secondNav: [{
            secondTitle: "充值统计",
            router: 'list5_1',
            icon: 'icon-chongzhi'
        }, {
            secondTitle: "支付统计",
            router: 'list5_2',
            icon: 'icon-zhifutijiao'
        }, {
            secondTitle: "消耗统计",
            router: 'list5_3',
            icon: 'icon-chaoshishangpinxiaohaojilu'
        }]
    }, {
        title: '商户管理',
        sort: '6',
        icon: 'icon-houtaidaohanglan_dianpu',
        secondNav: [{
            secondTitle: "账户管理",
            router: 'list6_1',
            icon: 'icon-zhanghu'
        }, {
            secondTitle: "充值管理",
            router: 'list6_2',
            icon: 'icon-chongzhi1'
        }, {
            secondTitle: "用户管理",
            router: 'list6_3',
            icon: 'icon-yonhu'
        }, {
            secondTitle: "订单管理",
            router: 'list6_4',
            icon: 'icon-74wodedingdan'
        }]
    }]
}